version: "3"

services:
  miemo-emotion:
    image: miemo/emotion
    build: ./Miemo-Emotion
    working_dir: /src/
    ports:
      - "5000:5000"
    volumes:
      - ~/emotion-static:/data
    command: python3 /src/emotion_server.py
