name: backend

on:
  push:
    branches: master

jobs:
  build_backend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: Api
    steps:
      - uses: actions/checkout@v2
      - name: init
        run: yarn
      - name: clean
        run: rm -rf /tmp/oldApi && mkdir /tmp/oldApi && mv ~/Api/ /tmp/oldApi/ && mkdir ~/Api && mv * ~/Api && rm -rf /tmp/oldApi
      - name: link_config
        run: ln -s ~/whitenoise/whitenoise.json ~/Api/whitenoise.json
