name: emotion

on:
  push:
    branches: master

jobs:
  build_backend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: Miemo-Emotion
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build -t miemo/emotion .
